name: Auto-Post Engine

on:
  schedule:
    # يعمل كل 10 دقائق
    - cron: '*/10 * * * *'
  workflow_dispatch: # يسمح لك بتشغيله يدوياً للتجربة

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Generator
        run: python amed.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-generate 200 new pages" || exit 0
          git push


